### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by TechnologyClassroom** [Bugswriter/notflix#13]
I see the project is GPLv3.  You should add a LICENSE file to make this visible at the first page view.  I can help with this if you want help.

Is this GPL-3.0-or-later or GPL-3.0-only?

**Comment by Bugswriter** [comment]
I added this.

**Comment by TechnologyClassroom** [comment]
@Bugswriter Thank you!  Is the project [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html) or [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html)?
