### ISSUE TITLE
You shouldn't run npm with sudo, please update that in the README

### ISSUE THREAD

**Issue by A-Siam** [Bugswriter/notflix#2]
check [this](https://wiki.archlinux.org/title/Node.js#Allow_user-wide_installations)

**Comment by walkxcode** [comment]
Running NPM with sudo is perfectly fine, just not preferred.

**Comment by Abhiwa6** [comment]
yes, even in my case webtorrent was unable to install until I provide npm root privileges

**Comment by Bugswriter** [comment]
this script isn't just for Arch.
Arch users will manually take care or this. 
Everywhere they ask to install npm packages with sudo ..so can't do anything.
