### ISSUE TITLE
Make notflix run in the terminal

### ISSUE THREAD

**Issue by ankushKun** [Bugswriter/notflix#23]
Make it run in the Terminal without needing dmenu or notify-send because they are not used my every user.
It will be better if the script can be run from the terminal and also choosing options from the terminal instead of a menu :<
also instead of notifications echo the stuff in the terminal

**Comment by Bugswriter** [comment]
hmm. I think it's better to add a flag to use notflix to split out magnet link and then user can just use it with webtorrent by his own.

**Comment by ankushKun** [comment]
Anything that makes it useable on other OSes

**Comment by hackerW1** [comment]
I think I can make it run in terminal wait for some time

**Comment by hackerW1** [comment]
> Anything that makes it useable on other OSes

Now I fixed it, check pull requests or I have a fork repo too so you can download it there.

**Comment by trianglecirclexyz** [comment]
I forked it and made it run in the terminal rather than use dmenu 
https://github.com/trianglecirclexyz/notflix-cli

**Comment by hackerW1** [comment]
> I forked it and made it run in the terminal rather than use dmenu https://github.com/trianglecirclexyz/notflix-cli

That's what I have done before you and rather terminal it has both options.

**Comment by trianglecirclexyz** [comment]
> 

ah nice, I didn't see that.

**Comment by ankushKun** [comment]
@hackerW1 welp
![image](https://user-images.githubusercontent.com/50258860/148068497-28e91373-2079-4c2b-8e30-338a64511907.png)

**Comment by ankushKun** [comment]
@trianglecirclexyz's fork works perfectly :D 
![image](https://user-images.githubusercontent.com/50258860/148069437-1c8b8a46-099e-42cb-be17-ddd8af952712.png)

**Comment by hackerW1** [comment]
> @trianglecirclexyz's fork works perfectly :D ![image](https://user-images.githubusercontent.com/50258860/148069437-1c8b8a46-099e-42cb-be17-ddd8af952712.png)

which one worked mine or his
