### ISSUE TITLE
Documentation on how to change the torrent source website

### ISSUE THREAD

**Issue by Feripe-a** [Bugswriter/notflix#24]
This is a good project. I'd like to use [Nyaa](https://nyaa.si/) with it. How one should properly modify your script to change the torrent source website?

**Comment by alpheratz0** [comment]
It is not as easy as just changing the url, you also need to change the parsing/scraping logic to extract the titles, seeders & leechers count

**Comment by yaemiku** [comment]
I wanted to do the same, so I [changed it](https://github.com/yaemiku/nyaa) - I hope it helps. Great project by the way :)

**Comment by Feripe-a** [comment]
> I wanted to do the same, so I [changed it](https://github.com/yaemiku/nyaa) - I hope it helps. Great project by the way :)

Imma take a look at it.
