### ISSUE TITLE
A way to disable the ability to search porn?

### ISSUE THREAD

**Issue by Edesem** [Bugswriter/notflix#27]
I can imagine that maybe this is not possible, but I want to get rid of all degeneracy from my life so I wonder if this is a feature that could somehow be implemented

**Comment by splpaul** [comment]
This is impossible to implement. You could have a list of banned keywords but that would not filter out everything, simply because you have no way of knowing that the p*rn is gonna be named a certain way or not

**Comment by Edesem** [comment]
yeah fair enough, how does google and duckduckgo implement safe search? is it just a large list of blocked words

**Comment by Willy-JL** [comment]
I seriously doubt that a small group of users on github can achieve the same level of filtering that a multi trillion dollar company like google has reached over 2 decades...

on the other hand tho, you could change *where* on 1337x it searches. [on line 20](https://github.com/Bugswriter/notflix/blob/498212c7d9d14866ebe45991b2a809487f0f56cb/notflix#L20) there is a commented search query that was supposedly user previously, and that searches by category... you could set it up to either search only porn or only movies or only whatever you want

**Comment by Bugswriter** [comment]
We don't want to complicate this thing. I know what happen when we try too much just through a shell script. It break.
also I am okay getting porn. It's a feature.

**Comment by Edesem** [comment]
Forked and was able to make it not search porn, although I dont get it BugsWriter. You had a line that literally makes it only search movies and not porn. https://github.com/Edesem/no-emoji-and-porn-notflix

**Comment by alpheratz0** [comment]
> Forked and was able to make it not search porn, although I dont get it BugsWriter. You had a line that literally makes it only search movies and not porn. https://github.com/Edesem/no-emoji-and-porn-notflix

That wont show TV, documentaries and anime results.

**Comment by Edesem** [comment]
Yeah I've realised that and am working on having the option to select which form of media you want to stream, only problem is I have no scripting experience so I'm just learning as I go lmao

**Comment by Edesem** [comment]
> > Forked and was able to make it not search porn, although I dont get it BugsWriter. You had a line that literally makes it only search movies and not porn. https://github.com/Edesem/no-emoji-and-porn-notflix
> 
> That wont show TV, documentaries and anime results.

Aight I fixed it now, it works fine
