### ISSUE TITLE
Notflix not working for me 

### ISSUE THREAD

**Issue by Filthyhqhq** [Bugswriter/notflix#3]
**/usr/local/bin/notflix: 18: Syntax error: redirection unexpected**

I am still new to linux. I did install webtorrent but it keeps showing the same error. What am I doing wrong??

**Comment by A-Siam** [comment]
The script is not posix complaint so it won't work on dash for example

**Comment by Filthyhqhq** [comment]
./notflix: line 61: notify-send: command not found
./notflix: line 69: webtorrent: command not found
./notflix: line 72: notify-send: command not found

**Comment by Filthyhqhq** [comment]
> The script is not POSIX complaint so it won't work on dash for example try
> 
> ```shell
> bash ./notflix
> ```
> 
> or link /bin/sh to bash (the default in arch, not recommended for eveyone)

**./notflix: line 61: notify-send: command not found
./notflix: line 69: webtorrent: command not found
./notflix: line 72: notify-send: command not found**

The search results do show up but when I click it this shows up

**Comment by A-Siam** [comment]
for notify-send please check the corresponding package for you distro 

for webtorrent check #5
