### ISSUE TITLE
No results selected. Exiting error

### ISSUE THREAD

**Issue by rernars** [Bugswriter/notflix#35]
When i search a movie in dmneu and press enter it doesnt show any results instead just gives me this error.
![image](https://user-images.githubusercontent.com/59098807/147887728-797f2390-c0ca-4b27-8bcb-a06d0bedb1df.png)

**Comment by alpheratz0** [comment]
Can you provide the output of the following command?: 
`bash -x notflix`

**Comment by rernars** [comment]
![image](https://user-images.githubusercontent.com/59098807/147980404-ff43af47-1856-4906-9828-44d83c57b8c8.png)

**Comment by rernars** [comment]
btw a little more detailed usage would be better, i assumed that i'am supposed to press enter after writing the movie name idk if that was what i was supposed to do.

**Comment by alpheratz0** [comment]
Which version of dmenu are you using?

**Comment by rernars** [comment]
dmenu-5.0

**Comment by alpheratz0** [comment]
> * dmenu -i -l 25

Ok, test the following commands in your terminal:
```sh
printf "a\nb\nc\nd\n" | dmenu -i
printf "a\nb\nc\nd\n" | dmenu -l 25
printf "a\nb\nc\nd\n" | dmenu -i -l 25
```
and tell me if one of them fails

**Comment by rernars** [comment]
umm all of them failed

**Comment by alpheratz0** [comment]
> umm all of them failed

I dont know whats happening but try building and installing dmenu from source:

```sh
sudo pacman -Rcns dmenu                   # uninstall dmenu
cd $(mktemp -d)                                     # go to temporary directory
git clone https://git.suckless.org/dmenu # get dmenu source 
cd dmenu
sudo make install                                   # build & install dmenu
```

**Comment by rernars** [comment]
Found the issue , i don't have dmenu installed, well not exactly but since i am using my own config of dmenu i didn't install it from any package manager , so it looks like this; 
![image](https://user-images.githubusercontent.com/59098807/149672641-dcc101fb-4c29-4114-a1e3-dd7ac81689a8.png)

if i install dmenu from paru or smt the program works flawlessly but when i do that it breaks my custom dmenu. so i will keep using stremio instead :)
thanks for taking your time to try and solve my problem.
