### ISSUE TITLE
Javascript error prompting the import of "Chalk"

### ISSUE THREAD

**Issue by cowmama7** [Bugswriter/notflix#38]
System running Linux Mint 20.1, system is up to date, Dmenu properly configured (I think), `sudo npm webtorrent-cli -g` run successfully
after running `bash ./notflix` and selecting a title, I am greeted with the enjoy watching window, and no video is played. Terminal displays the following error message:
```
/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:2
import chalk from 'chalk'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
Any ideas?

Additional info: All files are in their default state after running instructed install commands, reinstalling all packages leads to the same error.

**Comment by alpheratz0** [comment]
That problem is caused by webtorrent-cli, it requires a higher version of nodejs (14+). If you are using a debian based distro you can follow the instructions [here](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions) to install the latest version.

source: https://github.com/webtorrent/webtorrent-cli/issues/208

**Comment by cowmama7** [comment]
> That problem is caused by webtorrent-cli, it requires a higher version of nodejs (14+). If you are using a debian based distro you can follow the instructions [here](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions) to install the latest version.
> 
> source: [webtorrent/webtorrent-cli#208](https://github.com/webtorrent/webtorrent-cli/issues/208)

Everything functions properly now, Thank you!
