### ISSUE TITLE
Way to display more than 20 titles?

### ISSUE THREAD

**Issue by cowmama7** [Bugswriter/notflix#39]
It seems notflix caps out at 20 titles displayed, what can I alter in the notflix.sh file to change this cap to 50 or so?

**Comment by alpheratz0** [comment]
You need to get the number of pages, then the total number of results is around 20 * num_pages
```sh
num_pages=$(grep -Po '<li class="last"><a href="/search/game/\K[0-9]+(?=/">Last</a></li>)' "$cachedir/tmp.html") || num_pages=1
```
I will do a pull request with that feature soon
