### ISSUE TITLE
change `#!/bin/sh` to `#!/usr/bin/env bash`

### ISSUE THREAD

**Issue by A-Siam** [Bugswriter/notflix#4]
The script is not POSIX complaint and it will break on systems with minimal shells, dash as an example, linked to sh i.e. ubuntu 
 check #3

**Comment by Bugswriter** [comment]
but I have dash? it worked

**Comment by A-Siam** [comment]
That's weird, on my system ubuntu 20.04 with dash it doesn't work just like #3

**Comment by ignition-ctrl** [comment]
Yeah, on my Linux Mint system, dash doesn't work with the `<<<` operator.

**Comment by ShaqeelAhmad** [comment]
> but I have dash? it worked

Check what `/bin/sh` actually links to. If it still works try explicitly using `#!/bin/dash` .

Even shellcheck says dash doesn't support it. `shellcheck -s dash -S error ./notflix`

**Comment by Bugswriter** [comment]
doing something with bash when it can be done with shell .. no. Thanks @vveig4
