### ISSUE TITLE
subtitles?

### ISSUE THREAD

**Issue by FatSquare** [Bugswriter/notflix#45]
I don't see any option to enable subtitles for non-English movies

**Comment by alpheratz0** [comment]
![20220103203425](https://user-images.githubusercontent.com/93066036/147991897-447d06e1-6637-42de-93c9-36db1dd5437a.png)
That depends, if the video has subtitles you can switch between different supported languages clicking where the red rectangle is (mpv).

**Comment by mauricioquintela** [comment]
For subtitles included in the mkv file it works, it just doesnt work for subtitles included as a file (for example, .srt).

**Comment by mauricioquintela** [comment]
Just fyi, you can use an mpv script such as https://github.com/jonniek/mpv-filenavigator to manually navigate to the downloaded file's folder and manually sellect the subtitle files. You can also add the webtorrent temp folder as a favourite to make it easier to navigate there via editing the script and setting   `favorites = {'/tmp/webtorrent/', ...}`
