### ISSUE TITLE
cannot found dmenu and notify-send

### ISSUE THREAD

**Issue by jiajy0427** [Bugswriter/notflix#51]
I'm using Ubuntu on Windows

root@DESKTOP-PK7L829:/mnt/c/Users/Jialin# sudo curl -sL "https://raw.githubusercontent.com/Bugswriter/notflix/master/notflix" -o /usr/local/bin/notflix
root@DESKTOP-PK7L829:/mnt/c/Users/Jialin# sudo chmod +x /usr/local/bin/notflix
root@DESKTOP-PK7L829:/mnt/c/Users/Jialin# notflix
/usr/local/bin/notflix: 12: /usr/local/bin/notflix: dmenu: not found
/usr/local/bin/notflix: 28: /usr/local/bin/notflix: notify-send: not found

**Comment by Dichill** [comment]
I was tinkering on what was the problem with this one. At first I thought it was a python package, turns out it was part of a lib. To fix this issue simply enter this command in the terminal.

`sudo apt install libnotify-bin`

**Comment by krishaayjois21** [comment]
And use `sudo apt install dmenu` for dmenu

**Comment by alpheratz0** [comment]
> @Dichill @krishaayjois21 thank you for replies, but that didn't solve my issue completely, now it came out of a line says cannot open display, :(, any idea how I can fix it?

First you need to install and setup an X server, after that set the DISPLAY environment variable (export DISPLAY=:0)

Check [this](https://sourceforge.net/projects/vcxsrv) X server for windows.

**Comment by jiajy0427** [comment]
@alpheratz0  thanks bro, I really not familiar with X server, sorry for that, after I setup X server, I do have a search Torrent bar at the top of my screen after I call notflix on the command line, but I cannot type anything on the search bar, is there anything I can do about it?

**Comment by Jitendra300** [comment]
> @alpheratz0 thanks bro, I really not familiar with X server, sorry for that, after I setup X server, I do have a search Torrent bar at the top of my screen after I call notflix on the command line, but I cannot type anything on the search bar, is there anything I can do about it?

I myself can't write anything on the search bar, idk why, I am using debian 11, wayland, 
if someone can help me out, it would be great....

**Comment by 30p87** [comment]
I rewrote notflix in python (https://github.com/30p87/notflix.py), so it's natively compatible with every OS (in theory). Windows works, but installing the dependencies is hell

Note that it just uses stdin for input, as dmenu doesn't exist

**Comment by Dichill** [comment]
> I rewrote notflix in python (https://github.com/30p87/notflix.py), so it's natively compatible with every OS (in theory). Windows works, but installing the dependencies is hell
> 
> Note that it just uses stdin for input, as dmenu doesn't exist

thats a great project! You can try using QT to replicate what dmenu does. Although it would take a lot of time to recreate it, the result would be amazing.

**Comment by jiajy0427** [comment]
> I rewrote notflix in python (https://github.com/30p87/notflix.py), so it's natively compatible with every OS (in theory). Windows works, but installing the dependencies is hell
> 
> Note that it just uses stdin for input, as dmenu doesn't exist

thanks for the help man! i just saw how many dependencies it needs, god its troublesome

**Comment by 30p87** [comment]
Yes, I'm currently trying to automate the installation of the dependencies for windows too, but I rarely know Powershell. Luckily my dad is sysadmin and knows it far better, but currently I'm in school with only a vm on a ubuntu server at home accessable via vnc, but it's still really laggy, so I'll have results today evening at best

**Comment by 30p87** [comment]
> Yes, I'm currently trying to automate the installation of the dependencies for windows too, but I rarely know Powershell. Luckily my dad is sysadmin and knows it far better, but currently I'm in school with only a vm on a ubuntu server at home accessable via vnc, but it's still really laggy, so I'll have results today evening at best

So, the installer script now works. Note that I only tested it on a clean win 10 install in a vm, I don't have any safety mechanisms handling exceptions right now

https://github.com/30p87/notflix.py/tree/windows-(beta)

**Comment by ritchielrez** [comment]
Why installing deps in Windows is hell, it's seems to be normal for me. You guys can try out **scoop**, it's fantastic package manager, which has more packages than **winget**. It makes installing deps easier.

**Comment by 30p87** [comment]
> Why installing deps in Windows is hell, it's seems to be normal for me. You guys can try out **scoop**, it's fantastic package manager, which has more packages than **winget**. It makes installing deps easier.

Hell for someone that's used to apt install mpv nodejs python3

RN I have to install 7Zip, then download some package with binaries, extract them and move the mpv.exe into the same folder as the main script
Luckily have the other programs an installer so I can just quiet install them
