### ISSUE TITLE
`sudo npm install webtorrent -g` spits out the error: 613 error git@github.com: Permission denied (publickey). 613 error fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by Zigler21** [Bugswriter/notflix#6]
[2022-01-01T19_09_22_095Z-debug.log](https://github.com/Bugswriter/notflix/files/7798111/2022-01-01T19_09_22_095Z-debug.log)

**Comment by Zigler21** [comment]
I also tried 'sudo npm install webtorrent-cli -g' but it spit out this error: '1036 error An unknown git error occurred
1037 error command git --no-replace-objects ls-remote ssh://git@github.com/webtorrent/http-node.git
1038 error git@github.com: Permission denied (publickey).
1038 error fatal: Could not read from remote repository.
1038 error
1038 error Please make sure you have the correct access rights
1038 error and the repository exists.'

**Comment by Zigler21** [comment]
thats weird, I did: `sudo npm install webtorrent` and it worked?

might be a github issue, might have been down...

**Comment by RegalOctopus** [comment]
you shouldn't run npm with sudo as it will install node packages in root directory, instead of the global node directory.
here's a proper fix;
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
