### ISSUE TITLE
I am getting this issue...

### ISSUE THREAD

**Issue by quickcodes** [Bugswriter/notflix#7]

**Comment by quickcodes** [comment]
$ notflix
/home/dhruv/.local/bin/notflix: 13: dmenu: not found
/home/dhruv/.local/bin/notflix: 18: Syntax error: redirection unexpected

**Comment by soygustavo** [comment]
this error "/home/dhruv/.local/bin/notflix: 13: dmenu: not found" its solved by installing dmenu
sudo apt install suckless-tools

but i'm still getting this other one "18: Syntax error: redirection unexpected"

**Comment by Bugswriter** [comment]
or wait .. we ll make options for doing things with cli without dmenu.
