### ISSUE TITLE
link https://1337x.wtf doesnt work

### ISSUE THREAD

**Issue by Suwper** [Bugswriter/notflix#89]
the link https://1337x.wtf doesnt work as intended.

It can be fixed by changing the url to https://1337x.to.

fix:
#!/bin/sh

query=$(printf '%s' "$*" | tr ' ' '+' )
movie=$(curl -s https://1337x.to/search/$query/1/ | grep -Eo "torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/" | head -n 1)
magnet=$(curl -s https://1337x.to/$movie | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
peerflix -l -k $magnet

**Comment by DemonKingSwarn** [comment]
i kinda fixed that issue https://github.com/DemonKingSwarn/notflix

**Comment by Suwper** [comment]
> i still get
> /usr/local/bin/notflix: line 6: peerflix: command not found
> 

I had the same issue when reinstalling notflix, just do

git clone https://github.com/Bugswriter/notflix

then cd in the notflix directory and do

sudo cp -r notflix /usr/local/bin

hope this helps

**Comment by ShabirK21** [comment]
Im still getting the same error

**Comment by Suwper** [comment]
> Install peerflix first with npm
> `sudo npm install peerflix -g`

and mov or vlc if you havent

**Comment by sagastvme** [comment]
I live in Spain and that website is locked by the internet provider so I used this link https://1337x.unblockit.cat/ from unblockit.how
