### ISSUE TITLE
Issue while executing the script!

### ISSUE THREAD

**Issue by priyanshuSharma-WebDev** [Bugswriter/notflix#9]
Uhh, Bro, I think everything works fine but how do I stream that damn thing I mean I install webtorrent via npm but when I try to execute the script I've got the following error `line 69: webtorrent: command not found` even if I use `aria2c` the error still remains the same would you help me where did I get things wrong?

And Love from UK (Uttarakhand) :)

**Comment by choudhary-akash** [comment]
Install webtorrent-cli using `npm install webtorrent-cli -g`.
If it gives EACCESS error then do `sudo npm install webtorrent-cli -g`.

**Comment by ArekkusuMagni** [comment]
> Install webtorrent-cli using `npm install webtorrent-cli -g`. If it gives EACCESS error then do `sudo npm install webtorrent-cli -g`.

$ sudo npm install webtorrent-cli -g
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/webtorrent/http-node.git
npm ERR! /bin/bash: /root/.bashrc: Permission denied
npm ERR! Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-03T01_18_12_026Z-debug.log

This is the error I get when I run the command "sudo npm install webtorrent-cli -g"

**Comment by priyanshuSharma-WebDev** [comment]
you have to login to your github account via personal access token from your local computer then I think you won't face this problem again.

**Comment by miermontoto** [comment]
how did you login to github? i've been running into this issue for a few hours.

**Comment by priyanshuSharma-WebDev** [comment]
Setup authentication from github globally
Run the following command from the terminal
```
 git config --global user.name "your username"
 git config --global user.password <PERSONAL_ACCESS_TOKEN>
```

**Comment by miermontoto** [comment]
big thanks, npm is giving me a really hard time these days.

**Comment by ArekkusuMagni** [comment]
I am having issues with running the commands with my newly generated access token. This is the error message I get when I run the command. 

bash: syntax error near unexpected token `newline'

**Comment by priyanshuSharma-WebDev** [comment]
Try to execute commands properly it says that there is an unexpected newline character try to find out where is it or you can use (Ohh my zsh):D
